### ISSUE TITLE
React-Apollo: outdated part of the Authentication tutorial?

### ISSUE THREAD

**Issue by rhonivanpareja** [howtographql/howtographql#1029]
Good day friends 😄 This part of the tutorial does not work on me: _"You can verify that the new user is there by sending the users query in the dev Playground in the database project."_ . I could not query the `users` on my end, and it seems the syntax does not appear on the playground, its just the `feed` that i can only query.

Also, on the part of "Requiring authentication on the server-side" this [code](https://github.com/howtographql/react-apollo/blob/master/server/src/resolvers/Mutation.js) is different on my react project. This is the `post` part on my end

```js
function post(parent, args, context) {
  return context.prisma.createLink({
    url: args.url,
    description: args.description,
  })
}
```
this is on the tutorial:
```js
function post(parent, { url, description }, context) {
  const userId = getUserId(context)
  return context.prisma.createLink({
    url,
    description,
    postedBy: {
      connect: {
        id: userId
      }
    }
  })
}
```
Any clarifications on these parts? thanks :)

**Comment by moonquddus** [comment]
Same, although it's both `feed` and `info` that are the two queries that are available to me

**Comment by LeoSL** [comment]
Confirming the issue seems like the tutorial is using an old Playground's version. My current playground does *NOT* have the _database_ project as stated on the tutorial.

Tutorial's screenshot of Playground:
![image](https://user-images.githubusercontent.com/6999140/74618243-dee9c900-50fe-11ea-80b1-63a8a10fbdad.png)

My current Playground:
![image](https://user-images.githubusercontent.com/6999140/74618203-c2e62780-50fe-11ea-9ec3-64965feaf2e2.png)

As you can see, there's no left menu to choose between the projects.

**Comment by cobrabr** [comment]
Same here on both accounts.
