### ISSUE TITLE
graphene-python: Answer wrong for, In which Python class is defined the arguments for a Mutation?

### ISSUE THREAD

**Issue by aadarsh977** [howtographql/howtographql#1195]
As far as I have learned, the arguments for a mutation are defined in the `Arguments` subclass of `Mutation` class. But, the quiz says the correct answer is `Input`. Please correct.
![Screenshot](https://user-images.githubusercontent.com/10659454/99695235-737dbf00-2ab5-11eb-80ee-cc5e6f800942.png)

**Comment by ShatterPlayer** [comment]
Personally, I'm not sure what answer is correct but it seems to me also that it should be "Mutation".  Issue regards [Links and Voting](https://www.howtographql.com/graphql-python/5-links-and-voting/) lesson. Bug is apparently in [this file](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-python/5-links-and-voting.md) - in the column `correctAnswer` instead of 0 there ought to be 2.

**Comment by DrumsnChocolate** [comment]
Came across this while walking through the tutorial. If you were to ask me, I'd say that the right answer should be `Arguments`, not `Input`. Please do correct this, it seems very easy to fix.
