### ISSUE TITLE
New tuto in Typescript react for frontend with apollo client ? 

### ISSUE THREAD

**Issue by getzelus** [howtographql/howtographql#1411]
Hello,

I see that there is a new tutorial for the back end with node apollo server in Typescript (last update a week ago).
But the tutorial for the front end with apollo client is in JS and is old (last update 15 months ago)
We are the 24 of January 2022. 

Do you plan to make a new tutorial for the react front end with apollo client in Typescript ? 
It would be nice to have a complete recent fullstack tutorial in TS. 
Because its difficult to find that on internet. 

Concerning the backend, its a top recent tutorial. 
But i wonder if it would be possible to add the upload of file (picture) with GraphQL and the real time with subscriptions ? 

Thanks in advance.

**Comment by TasinIshmam** [comment]
Hi @getzelus  :wave: 

First of all, thank you for your feedback! 

> Do you plan to make a new tutorial for the react front end with apollo client in Typescript?

This isn't a big priority for us at the moment as we're a bit understaffed in terms of maintainers/active contributors. However, if someone from the community is interested in contributing such a tutorial, we'd be super happy to assist in any way. 

> Concerning the backend, its a top recent tutorial.
 
Thanks for the kind words! 

> But i wonder if it would be possible to add the upload of file (picture) with GraphQL and the real-time with subscriptions?

That's interesting. I think file upload is something that is definitely possible (though it isn't planned at the moment and likely wouldn't perfectly align with the structure of existing tutorials). 

Regarding subscriptions, we're unfortunately in a more difficult situation. Since [Apollo has phased out built-in support for subscription in Apollo Server v3](https://www.apollographql.com/docs/apollo-server/data/subscriptions/), there's a very good chance that the typescript tutorial will not cover it to avoid the complexity of workarounds. However both the [old javascript apollo server tutorial](https://www.howtographql.com/graphql-js/0-introduction/) and the [new typescript helix tutorial](https://www.howtographql.com/typescript-helix/0-introduction/) cover subscription, so these might be useful resources to learn more about this topic. 

Hope this was helpful :smile:

**Comment by getzelus** [comment]
Thanks for your answer.

Its strange that complete modern fullstack TS GraphQL tutorials are difficult to find.
Cause it looks like a new standard for modern top companies.
I dont know how these developers learnt to do their job. 
And its like their secret is kept. 
They can learn from different parts of the web but they have to fix the puzzle themselves without a complete guide.

**Comment by TasinIshmam** [comment]
We're actually working on a four-part fullstack typescript tutorial series with Next.js and TypeScript at Prisma. This might be something you find interesting as it covers the front-end. Additionally, the final part, when released will cover file upload with GraphQL.  

You can find the first part [here](https://www.prisma.io/blog/fullstack-nextjs-graphql-prisma-oklidw1rhw) :smile:
