### ISSUE TITLE
Dark mode(Theme options) will  be good for UX and DX

### ISSUE THREAD

**Issue by EngrGord** [howtographql/howtographql#1430]
The whiteness of the background makes getting through the tutorial more challenging than it should be for people with light sensitivity issue.
And its 2022.
Would like to make a pull request on this if no one is working on it.
Thanks for your efforts.

**Comment by TasinIshmam** [comment]
Hi @EngrGord  

I totally understand your point and appreciate your offer to work on this! You are free to work on this and we will accept PRs for it. 

However, the code for the website itself is pretty out of date and not really well documented. We are strongly considering doing a full redesign (with the help of some other interested parties) sometime this year, but haven't had the capacity to take on the project yet. 

With that in mind, I'm not sure if it will be worth your time working on the website as it is (since it's likely going to change soon).

**Comment by EngrGord** [comment]
hey,
Thanks for reaching out, I understand your point and it makes sense.
Since i don't have an idea the technologies or design system that will be used for a redesign, it might not be a good idea working on this yet.
It has been wonderful taking the the GraphQL course and I appreciate the simplicity and clarity.

I'll be looking forward to a better website.
