### ISSUE TITLE
React Apollo Pagination tutorial does not refetch data?

### ISSUE THREAD

**Issue by scotmatson** [howtographql/howtographql#177]
I was trying out the Apollo-Client as in lieu of Relay as it provides better support for offset-based pagination. Following the tutorial at https://www.howtographql.com/react-apollo/9-pagination/, when the _nextPage() event is triggered the page paginates forward but data is not being fetched.

It isn't exactly mentioned in this tutorial what is handling the refetch and I'm wondering if I overlooked something or if this could be better implemented to address a more general use case.

The Apollo documentation uses `fetchMore`, but this isn't really a correct solution for offset-based pagination as much as it is more for cursor based pagination. http://dev.apollodata.com/react/pagination.html#numbered-pages. However changing this `feed: [...previousResult.feed, ...fetchMoreResult.feed]` to simply `feed: [...fetchMoreResult.feed]` does achieve a more offset-like result, so perhaps I'm being overly picky in respects to that.

I noticed there is `refetchQueries` that looks like a possible solution http://dev.apollodata.com/react/cache-updates.html#refetchQueries but am inexperienced with this client and am wondering if I'm missing something or if this tutorial should be revisited/updated.

**Comment by oredi** [comment]
I had the same issue as well although I was working on the new version of Apollo Client 2. So hopefully I will not be confusing anyone here. I managed to find a piece of documentation in Apollo Client about an option named [FetchPolicy](http://dev.apollodata.com/react/api-queries.html#graphql-config-options-fetchPolicy) . It appears that FetchPolicy is defaulted to cache-first and so debugging the Pagination code showed that the pages were being moved by the data was loaded from the store in Apollo Client instead of firing a call to the GraphCool server.

I managed to get around that by setting that option to  'cache-and-network' when exporting the LinkList Component
`export default graphql(ALL_LINKS_QUERY, {
   name: 'allLinksQuery',
   options: (ownProps) => {
     const page = parseInt(ownProps.match.params.page, 10);
     const isNewPage = ownProps.location.pathname.includes('new');
     const skip = isNewPage ? (page - 1) * LINKS_PER_PAGE : 0;
     const first = isNewPage ? LINKS_PER_PAGE : 100;
     const orderBy = isNewPage ? 'createdAt_DESC' : null;

     return {
       variables: { first, skip, orderBy },
       fetchPolicy: 'cache-and-network'     // Apollo Client 2 sets this to cache-first which will grab stale data from the store
     };
   }
})(LinkList);`

I have a version of the tutorial using Apollo Client 2 and the latest subscriptions-transport-ws if you are interested [React Apollo Client v 2.0](https://github.com/oredi/howtographql-react-apollo)

**Comment by nikolasburk** [comment]
Apologies for the late response @scotmatson! I believe this issues has been fixed with the latest update of the React & Apollo tutorial to Apollo Client 2.0. If you still have questions, please open an issue in the [`react-apollo`](https://github.com/howtographql/react-apollo) repo 🙂
