### ISSUE TITLE
Phrasing for tutorial "paste code below"

### ISSUE THREAD

**Issue by wking-io** [howtographql/howtographql#213]
I think that it is always more beneficial when learning to never paste code and to type it all out as you go. It forces reflection on ever line and gets people more familiar with syntax. 

Just wanted to throw this out there and see there are strong feelings for changing instances of "Then paste the following code" to something more along the lines of "Then enter/add the following code below"

**Comment by nikolasburk** [comment]
Hi @wking-io! First, my sincere apologies for the late response! 

I fully agree with you that typing out the code is a lot more instructive and helps understand what's going on a lot better! While I won't make any immediate updates to the tutorials right now (due to time constraints), I will definitely keep your suggestion in mind for future updates. Thanks! 🙏
