### ISSUE TITLE
this.props.relay.environment._network.fetch is not a function 

### ISSUE THREAD

**Issue by burnick** [howtographql/howtographql#222]
Unhandled Rejection (TypeError): _this.props.relay.environment._network.fetch is not a function
Link._callee2$

**Comment by janbejvl** [comment]
Any updates on this?
It might help to downgrade packages react-relay, relay-compiler and babel-relay-plugin to version 1.1.0 instead of currently latest version 1.3.0. This solved problem for me with presence of fetch in the _network object, but another different problem with updater function appeared.

**Comment by nicerr** [comment]
Sure enough... downgrading to react-relay@1.2.0 [`yarn add react-relay@1.2.0`] solved the problem for me.

It appears react-relay@1.3.0 has left a few -network functions. After putting a breakpoint in Chrome before the network fetch line, using react-relay@1.2.0 this shows: 

![screen shot 2017-09-20 at 2 20 34 am](https://user-images.githubusercontent.com/1907478/30621648-90bcb9f2-9dac-11e7-9e5c-6a77b33aea72.png)

and using react-relay@1.3.0 this shows:

![screen shot 2017-09-20 at 2 30 42 am](https://user-images.githubusercontent.com/1907478/30621649-90c4b1a2-9dac-11e7-8b35-678179e88dbf.png)

It appears that the functions fetch, request, and requestStream have disappeared in 1.3.0?

Is this by design or error?

**Comment by nicerr** [comment]
#https://github.com/facebook/relay/issues/2110#issuecomment-330721856

> this is not a public api, you should avoid using like this

#https://github.com/facebook/relay/issues/2110#issuecomment-330722289

> _ prefix is a convention we use for private properties. I'm not sure what the use case is here, but you should probably use a QueryRenderer or refetch container here.
> We've made some changes to the network layer recently to allow more complex network response formats like potential streaming. The Network module is pretty much internal API.

**Comment by ra8ga** [comment]
any updates? I assume that refetch container may be a good option?
