### ISSUE TITLE
Login as a query

### ISSUE THREAD

**Issue by nsanitate** [howtographql/howtographql#429]
Why I should implement `Login` as a mutation and not as a query?
Ref: [Implementing the login mutation](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-js/4-signup-and-login.md#implementing-the-login-mutation)

**Comment by nikolasburk** [comment]
Hey @nsanitate, that's a great question!

As you imply by your question, the `login` could also be implemented as a query. Here's my perspective on it:

- Anything that changes state or causes some sort of side effects on the server should be a mutation. 
- Anything that has no side effects at all should be a query.

The reason why `login` falls into the first category is because it changes the "state of the world" (not the one of the database): After the operation you can see things you weren't able to see before. This must have been causes by some sort of side effect.

Another short argument: It can sometimes make sense to cache the result of a query, but never a mutation. And it would never make sense to cache the result of a `login` operation.
