### ISSUE TITLE
Error: Not authenticated

### ISSUE THREAD

**Issue by eugenegodun** [howtographql/howtographql#448]
I've launched dev server and was trying to make mutations like here [react-apollo/1-getting-started](https://www.howtographql.com/react-apollo/1-getting-started/)

`mutation CreatePrismaLink {
  post(
    description: "Prisma turns your database into a GraphQL API 😎",
    url: "https://www.prismagraphql.com"
  ) {
    id
  }
}`

`
mutation CreateApolloLink {
  post(
    description: "The best GraphQL client for React",
    url: "https://www.apollographql.com/docs/react/"
  ) {
    id
  }
}`

But I got the error. Any ideas?

```
Server is running on http://localhost:4000
Serving playground at http://localhost:3000/playground
Error: Not authenticated
    at getUserId (/Users/eugenegodun/Documents/Projects/hackernews-react-apollo/server/src/utils.js:12:9)
    at post (/Users/eugenegodun/Documents/Projects/hackernews-react-apollo/server/src/resolvers/Mutation.js:6:18)
    at field.resolve (/Users/eugenegodun/Documents/Projects/hackernews-react-apollo/server/node_modules/graphql-extensions/lib/index.js:119:77)
    at resolveFieldValueOrError (/Users/eugenegodun/Documents/Projects/hackernews-react-apollo/server/node_modules/graphql/execution/execute.js:544:18)
    at resolveField (/Users/eugenegodun/Documents/Projects/hackernews-react-apollo/server/node_modules/graphql/execution/execute.js:508:16)
    at /Users/eugenegodun/Documents/Projects/hackernews-react-apollo/server/node_modules/graphql/execution/execute.js:330:20
    at <anonymous>
```

**Comment by JonathanSum** [comment]
I have this problem too. I have no ideas what it is.

**Comment by I-keep-trying** [comment]
I'm having the exact same problem! I googled and found this issue, great.

**Comment by JonathanSum** [comment]
So..what is the issue? I can only find this page.

**Comment by I-keep-trying** [comment]
I have found nothing but more people with the same exact issue. [This is not exactly the same](https://www.prismagraphql.com/forum/t/cannot-open-playground-your-token-is-invalid/2194) but it might help. I'm ready to give up and try another completely different back end to start with. The graphql forum might have more, but you have to sift through the content carefully because it includes their "graphcool" product which is similar, but different enough to be irrelevant.

**Comment by eugenegodun** [comment]
@I-keep-trying @JonathanSum It seems like I don't have this bug anymore maybe somebody has fixed it. Please check it again.

**Comment by danielsbird** [comment]
The tutorial is missing a step. In order to successfully execute the `post` mutation you need to include a bearer token. 

**Step 1: Get a bearer token:**
You can get a token by executing the [signup](https://github.com/howtographql/graphql-js/blob/master/src/schema.graphql#L14) mutation in the playground to create a new user. This is the signup mutation I ran:
```
mutation {
            signup(email: "jane@example.com", name: "Jane Doe", 
            password: "mypassword") {
            token
        }
}
```

**Step 2: Include the bearer token in your request**

Notice there is a text area called _HTTP HEADERS_ at the bottom of the playground. Paste the following code into _HTTP HEADERS_, replacing `your-token-goes-here` with the bearer token returned by the server in step 1:

```
{
    "Authorization": "Bearer your-token-goes-here"
}
```

**Step 3: Run the `post` mutation**

Now that you are including a bearer token in your request you can run the `post` mutation. You should get a response similar to this:

```
{
  "data": {
    "post": {
      "id": "cjffqzrrbkmmc0b817rcglta3"
    }
  }
}
```

**Comment by tstewart15** [comment]
This also seems to be an issue once you get to Chapter 3:
![image](https://user-images.githubusercontent.com/8942170/38176555-2dc8b7d2-35bf-11e8-8422-39ec2ebf8373.png)

**Comment by nikolasburk** [comment]
Thanks @danielsbird, your solution definitely works! 

However, if you're following the steps in the tutorial and download the server code from the `starter` branch of the repo, it shouldn't be necessary. The `starter` branch of the repo has a version of the server [where authentication is not required](https://github.com/howtographql/react-apollo/blob/starter/server/src/resolvers/Mutation.js#L6). It is only changed in the [authentication](https://www.howtographql.com/react-apollo/5-authentication/) chapter of the React & Apollo tutorial.

**Comment by danielsbird** [comment]
@nikolasburk You are right. I should have read the instructions more carefully. Instead of downloading the starter branch like the instructions say I cloned the master branch. Thanks for your help.

**Comment by onurarpapay** [comment]
@danielsbird this solution doesn't work for me but the error message is changed. It says now "invalid signature".

**Comment by onurarpapay** [comment]
@nikolasburk First, thanks for such a great tutorial. It really covers the basics of working with graphql. I just have a comment. The one liner about "If you are on Windows, you may want to install Git CLI to avoid potential problems with commands such as curl." is in fact not helping Windows users that much. Having Git CLI installed alone doesn't make the command you wrote run, since Windows is missing curl. Moreover, downloading the server code from `starter` branch is never mentioned in the tutorial. It is just contained within the "curl" command that Windows users are not able to use. It is hard to infer from there that we must download the starter branch to continue the tutorial. 

I will appreciate if you include clearer instructions for Windows users to download `starter` branch manually and only extract the server folder. 

Thank you for your effort that you put in writing this tutorial.

**Comment by vctormb** [comment]
@onurarpapay I've just opened Git Bash and pasted the curl command. It worked fine here. Btw, I'm using Windows too.
