### ISSUE TITLE
GraphQLError: Syntax Error GraphQL

### ISSUE THREAD

**Issue by caeugusmao** [howtographql/howtographql#520]
Hi,

I am trying to follow the graphql tutorial using react + apollo and I cannot pass through "Exploring the server" step. When the playground webpage is loaded, the database model works but app model does not work.

In the server console log I receive this error:

**{ GraphQLError: Syntax Error GraphQL request (38:3) Expected Name, found String

37: type BatchPayload {
38:   """
      ^
39:   The number of nodes that have been affected by the Batch operation.
    at syntaxError (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/error/syntaxError.js:30:15)
    at expect (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:972:32)
    at parseName (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:90:15)
    at parseFieldDefinition (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:715:14)
    at any (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:1008:16)
    at parseObjectTypeDefinition (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:685:16)
    at parseTypeSystemDefinition (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:609:16)
    at parseDefinition (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:150:16)
    at parseDocument (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:108:22)
    at parse (/Users/carlos.gusmao/workspace/playground/hackernews-react-apollo/server/node_modules/prisma-binding/node_modules/graphql-tools/node_modules/graphql/language/parser.js:45:10)
  message: 'Syntax Error GraphQL request (38:3) Expected Name, found String\n\n37: type BatchPayload {\n38:   """\n      ^\n39:   The number of nodes that have been affected by the Batch operation.\n',
  locations: [ { line: 38, column: 3 } ],
  path: undefined }**

Could you help me to understand what is happening and how can I solve this issue? It seems some error in prisma.graphql file, but this file is auto generated, I dont't know how can I solve this.

I am using node 8.9.4, the last stable version.

Thanks for help!!!!

**Comment by DevNicoT** [comment]
Hi @caeugusmao ,

Are you able to open the playground, right? What query/mutation are you trying when the console logs that message? The error _seems_ to come from there.

**Comment by caeugusmao** [comment]
Hi @DevNicoT ,

First of all thanks for quick and answer!

Yes I am able to open the playground. This is happening before I try to run any query. I run "yarn dev", the playground has already opened with error as I can show you below.

![screen shot 2018-02-27 at 2 10 10 pm](https://user-images.githubusercontent.com/2955469/36743026-f67a99dc-1bc7-11e8-8252-d57d4260f2de.png)

This error already shows in my console log too as I wrote in first message.

**Comment by DevNicoT** [comment]
@caeugusmao ,

To be honest, I don't know if this is related, but let's give it a shot, maybe it helps. :)

I just noticed, according to the path described in your error log, that you seem to have the `server` folder directly within the `hackernews-react-apollo`, instead of inside `src` folder (as per the tutorial's indications).

So I have to ask, did you face any problem when downloading the Node's project code for the 'built-in backend' for this project? Are you fully sure you included the `server` at the end of this `curl`:

`curl https://codeload.github.com/howtographql/react-apollo/tar.gz/starter | tar -xz --strip=1 react-apollo-starter/server`

... and that it actually worked as expected, downloading the `server` folder within your `src` folder?

If unsure, I'd suggest you start it again, and check so to make sure this works as expected. Worst case scenario, if this doesn't solve anything, at least we tick this off from the list.

**Comment by munkhorgil** [comment]
@caeugusmao Did you replace **PRISMA_ENDPOINT** placeholder by output of deploy command **HTTP** endpoint ?

**Comment by DamonJJ** [comment]
To chime in, I am having this exact error. @DevNicoT when `curl https://codeload.github.com/howtographql/react-apollo/tar.gz/starter | tar -xz --strip=1 react-apollo-starter/server` or the command from the tutorial `curl https://codeload.github.com/howtographql/react-apollo/tar.gz/starter | tar -xz --strip=1 react-apollo-starter/server` is ran it install the server folder outside the src like below:

![image](https://user-images.githubusercontent.com/5857861/37190803-cad9f62e-2310-11e8-9a13-020a4f288248.png)

However once I move the server folder inside src it still gives the error.

**Comment by DamonJJ** [comment]
@caeugusmao The PRISMA_ENDPOINT placeholder was replaced by the http endpoint in my app.

**Comment by DevNicoT** [comment]
Exactly same error log, @DamonJJ ? 
Just in case, could you both check your `server/src/generated/prisma.graphql` file? What do you have in the definition of type BatchPayload?

**Comment by DamonJJ** [comment]
@DevNicoT  Thank you for your reply 🥇 

Below is the type:

`type BatchPayload {
  count: Long!
}`

**Comment by DevNicoT** [comment]
@DamonJJ First of all, sorry that the last few days I couldn't come back to check this.

Second, yes, sorry, you're right about the `server` folder. I might have accidentally done the `curl` thing from inside the `src` folder any time. :)

Third: yes, that `BatchPayload` definition should be right, as long as you also have the `scalar Long blah, blah` later on that file.

Now, going to the point, I really have continued trying to reproduce your error but I can't.

I remember I had a problem with the ports annoying each other (front/backend) and someone here helped me by pointing me to this: 

- if you're on a Mac, open your `hackernews-react-apollo/package.json`, change the `start` script's value to: `"PORT=3006 && react-scripts start"`.
- if you're on Windows, first make sure to use the [Git bash](https://git-scm.com/) and, instead, change that script for this: `"set PORT=3006 && react-scripts start"`

Basically what you're doing is avoiding that the playground and the front end fight for port 3000. Instead, you assign another one (3006 in this case, or whatever else you choose) to the React front end.

Then, when you type `yarn dev` there will be nothing on port 3000. Would that help in your case? Otherwise, **_what is the log in the terminal after you type_** `yarn dev`?

I also have to ask: **_you're not yet making any query/mutation when you receive the error, right?_** If you are, it would be great that you share it here.

Lastly, if not yet solved, I'd suggest you **_start it all over again, and post here a step-by-step list of the steps followed as you do them_**, hopefully that will solve the mystery, and also allow me (or someone else) to reproduce the error and identify the source of the issue.

HTH!

**Comment by DevNicoT** [comment]
Cool, @DamonJJ !! :)

We haven't heard anymore about you @caeugusmao , did any of these solve your issue, too?
Can we then close it?
Thank you in advance!

**Comment by smcelhinney** [comment]
What?!?! Pay it forward dude, how did you resolve it?

**Comment by swcarlosrj** [comment]
Thanks @caeugusmao for opening this issue 😄.It should be fixed. Closing this!

**Comment by bekundan** [comment]
// @flow strict

import { type Source } from '../language/source';

import { GraphQLError } from './GraphQLError';

/**
 * Produces a GraphQLError representing a syntax error, containing useful
 * descriptive information about the syntax error's position in the source.
 */
export function syntaxError(
  source: Source,
  position: number,
  description: string,
): GraphQLError {
  return new GraphQLError(`Syntax Error: ${description}`, undefined, source, [
    position,
  ]);
}


############# Here in this code show error in syntaxError.js.flow
