### ISSUE TITLE
Change for apollo-cache-inmemory v 1.1.12

### ISSUE THREAD

**Issue by StefanoDeVuono** [howtographql/howtographql#626]
I've been fiddling around with `apollo-cache-inmemory` version 1.1.12 and I notice the tutorial instructions of how to send result don't work as expected. The `result` object returned from `updateQuery` in `LinkList.js` needs its feed to have a `__typename: 'Feed'`. Otherwise, the cache's  `writeFieldToStore` function (in writeToStore.js ln 302 or writeToStore.ts ln 440) error out for lack of typename.

```
const result = {
  ...previous,
  feed: {
    links: newAllLinks,
    __typename: 'Feed'
  },
}
```

Please note as, once `apollo-client-preset` updates its required version of `apollo-cache-inmemory` to 1.1.12, this will become a bug.

Should I submit a PR to change the docs?

**Comment by elliotaplant** [comment]
Two more solutions would be to either use the rest operator to copy the whole feed object when we update it:
```javascript
const result = {
  ...previous,
  feed: {
    ...previous.feed,
    links: newAllLinks,
  },
}
```
Or to just change the `links` property of the `feed` instead of re-assigning the whole `feed` object:
```javascript
previous.feed.links = newAllLinks;
return previous;
```
Both would fix the `Store error: ...` without having to manually set the `__typename`, and would prevent breaks in the future if the name of the type `Feed` changed to something like `LinksFeed`.

**Comment by swcarlosrj** [comment]
Thanks @StefanoDeVuono for opening this issue 😄. it should be fixed. Closing this!
