### ISSUE TITLE
gatsby v2 upgrade path?

### ISSUE THREAD

**Issue by sw-yx** [howtographql/howtographql#771]
Hi folks!

just wondering what the maintenance/upgrade path is. I tried running this locally but couldnt get it to work - seems like some dependencies are pinned to `@next` and that's shifted so much that the project no longer runs. would love to see this upgraded to gatsby v2. might be able to loop in the gatsby folks for help.

Shawn

**Comment by toddb** [comment]
For anyone reading this, you may be here because you couldn't compile a local version as well. After a few false starts, my solution was obvious that I wan't running the correct version of node (I was on v10).

It is all documented in the `.nvmrc`.

```bash
nvm install 7.9.0
```

I hope that helps some. I know this isn't about upgrade to v2.

**Comment by sw-yx** [comment]
yeah. i tried forking and upgrading to v2 and it was a mess. the gatsby-node may need to be reworked from scratch if this were ever to be upgraded to v2 (which it doesnt have to be)

**Comment by swcarlosrj** [comment]
@sw-yx @toddb thanks for the feedback. At the moment we're gonna try to fix all the issues & merge PRs, after that we'd discuss how we can improve the platform. I'd let you know in case that'd be possible 😄
